# Generated by Django 5.0.4 on 2024-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
    ]
