# Generated by Django 5.0.4 on 2024-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.IntegerField(default=0, verbose_name="Счетчик просмотров"),
        ),
    ]
